### ISSUE TITLE
TransitionViews does not work with `react-helmet` and SSR

### ISSUE THREAD

**Issue by jperasmus** [AndreasFaust/gatsby-plugin-transitions#14]
Hi there,

Something I picked up now. When using the `<TransitionViews>` component with `react-helmet`, the meta tags are not set for server-side rendering. It works fine once the client is hydrated.

A quick and easy fix that I applied is to check for `typeof window === 'undefined'` in the `src/transitions/views.js` component file and then directly setting the `children` within the `<div className="views">` wrapper component.

**Comment by AndreasFaust** [comment]
Thank you for reporting! I’ll fix this ASAP.

**Comment by agrohs** [comment]
Any update on here/same of code fix?
