### ISSUE TITLE
Is it possible to avoid creating a `layouts/index.js` structure?

### ISSUE THREAD

**Issue by rchrdnsh** [AndreasFaust/gatsby-plugin-transitions#2]
I am using `gatsby-plugin-layout` already in my site, so could I just import the `TransitionProvider` into my Layout.js file?

Is making a `Layouts` folder and then adding a redundant `index.js` file necessary?

I don't understand the approach. If it is necessary then are there any explanations out there on the interwebs?

Thanks ! XD

**Comment by AndreasFaust** [comment]
You just have to wrap your views with the `TransitionProvider`. How your `layout`-file or -folder is called is unnecessary.

**Comment by rchrdnsh** [comment]
ok, chill :-)
