### ISSUE TITLE
How can I speed up the fade?

### ISSUE THREAD

**Issue by rchrdnsh** [AndreasFaust/gatsby-plugin-transitions#4]
The fade animation looks nice, but it's a bit slow. Is there a way to speed up the fade a bit?  I did not see that explicitly stated in your readme, I do believe.

Thanks! XD

**Comment by AndreasFaust** [comment]
A fast animation-setting is:
```
config: {
  mass: 1, 
  tension: 210, 
  friction: 20,
  clamp: true
}
```
Add this to the `enter` and `leave` prop.

**Comment by AndreasFaust** [comment]
Have a look at the `readme.md` again. I have updated it with an example (see: **4. Customize**).

**Comment by rchrdnsh** [comment]
This worked, thank you XD
