### ISSUE TITLE
Add navigate helper function with transition

### ISSUE THREAD

**Issue by dodikuswono** [AndreasFaust/gatsby-plugin-transitions#6]
### Feature request:
It would be nice to have navigate helper function to navigate programmatically with transition.

Thanks.

**Comment by AndreasFaust** [comment]
You can do this already. To emphasize it, I created the topic **Navigate programmatically** in the `readme.md`.

**Comment by dodikuswono** [comment]
Thanks. I don't notice it.

But looks like I cannot use useTransitionStore & dispatch outside of TransitionProvider yet ? 
I've an error when use it in main layout:
> TypeError: Cannot read property '0' of undefined

**Comment by dodikuswono** [comment]
I've workarround this problem by set TransitionProvider props from state, before navigate with Gatsby navigate helper function. It's work for my use case.

Thanks a lot for the lib :)
