### ISSUE TITLE
Question: Can I enable scroll to top for some routes?

### ISSUE THREAD

**Issue by rchrdnsh** [AndreasFaust/gatsby-plugin-transitions#8]
I would like to do what the subject line says for a few routes. Is that possible in some way? For example, I want the blog list to scroll to top when an individual blog post is clicked, otherwsie it moves to the middle of the post, or something like that...

**Comment by rchrdnsh** [comment]
To be clear, right now all of the routes in my app do NOT scroll to the top EVER, which breaks the user experience in many instances. For example, if a user scrolls down the home page quite a bit until they get to the blog section, then click on a link to a blog post, the new route does not start at the top of the blog post, but right in the middle of the post somewhere, which makes the experience very disorienting. Also, if a user then clicks the home button from ay page at any scroll position, they are dropped off somewhere down the home page, rather than back at the top.

I would WANT the forward and back buttons to not lose the last scroll position of the last page, and not scroll to the top, but to also NOT keep the position of the current page, which just makes navigating the app extremely confusing.

I've been trying to control the scroll behavior more in the `gatsby-browser.js` file but nothing seems to work, even telling Gatsby to reset every single route.

Please help if you can, as I don't know what I'm doing and it's all driving me a little kooky 🥴

**Comment by AndreasFaust** [comment]
Thank you for reporting this issue. It is very important for me, to know what goes wrong in setups different from mine. **The best way to solve this together, would be a test-repo.**
What I can say at this point: the plugin does not retain the scroll-position on moving for- and backwards yet, but I am working on fixing this. Nevertheless on my sites it always unveils new routes with scroll-y-position 0, except I define the prop `y`. So I need more information from you reproduce this bug.

**Comment by rchrdnsh** [comment]
Yeah, I'm working on trying to isolate the issue as best as I can. Give me a few days to see if I can get this down to a smaller size and really nail where the issue might be coming from.

**Comment by rchrdnsh** [comment]
I'm digging deep and it might actually be interactions between multiple plugins, which may or may not include yours. I'll close for now, but report anything I find or re-open if need be.
